<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1">
  <context>
    <name>AnalysisService</name>
    <message>
      <location filename="../fontgallery/services/analysis.py" line="137" />
      <source>The extracted master collection does not exist: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/analysis.py" line="146" />
      <source>No extracted fonts were found in: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/analysis.py" line="162" />
      <source>Starting analysis of {count} extracted fonts</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/analysis.py" line="192" />
      <source>Analyzed font {current}/{total_fonts}: {font}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/analysis.py" line="218" />
      <source>Copied Spanish subset: {count} fonts</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/analysis.py" line="234" />
      <source>Copied technical subset: {count} fonts</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/analysis.py" line="268" />
      <source>Copied {count} fonts to {label}</source>
      <translation type="unfinished" />
    </message>
  </context>
  <context>
    <name>CardGenerationService</name>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="79" />
      <source>Main album</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="87" />
      <source>Spanish album</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="95" />
      <source>Technical album</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="115" />
      <source>Starting PNG card generation</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="168" />
      <source>Skipped card for {font} due to rendering error: {error}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="179" />
      <source>Rendered card {current}/{total_cards} for {label}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="186" />
      <source>Generated {count} PNG cards for the {label} album in {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="206" />
      <source>Missing extracted-font directory: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="218" />
      <source>No extracted fonts were found in: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="303" />
      <source>Generated by FontGallery from locally extracted fonts.</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="317" />
      <source>Pillow is required for PNG card generation. Install the Python package 'Pillow' or the Debian package 'python3-pil'.</source>
      <translation type="unfinished" />
    </message>
  </context>
  <context>
    <name>ExtractionService</name>
    <message>
      <location filename="../fontgallery/services/extraction.py" line="98" />
      <source>No font .deb packages were found in: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/extraction.py" line="114" />
      <source>Starting font extraction from {count} packages</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/extraction.py" line="125" />
      <source>Processing package: {package}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/extraction.py" line="164" />
      <source>  Accumulated fonts: {count}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/extraction.py" line="173" />
      <source>Processed package {current}/{total}: {package}</source>
      <translation type="unfinished" />
    </message>
  </context>
  <context>
    <name>FlatCardExportService</name>
    <message>
      <location filename="../fontgallery/services/flat_card_export.py" line="43" />
      <source>No PNG cards were found in: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/flat_card_export.py" line="58" />
      <source>Starting flat PNG export for the {label} album</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/flat_card_export.py" line="70" />
      <source>Copied flat card {current}/{total}: {file}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/flat_card_export.py" line="78" />
      <source>Copied {count} PNG cards into the flat folder: {path}</source>
      <translation type="unfinished" />
    </message>
  </context>
  <context>
    <name>HtmlGenerationService</name>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="109" />
      <source>Starting HTML generation for 3 albums</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="179" />
      <location filename="../fontgallery/services/html_generation.py" line="147" />
      <source>Main album</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="149" />
      <source>Album of extracted fonts from .deb packages</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="150" />
      <source>Generated from locally extracted font packages and intended for general graphic design browsing. Technical and math-oriented fonts are excluded from this main album.</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="164" />
      <source>Technical fonts excluded from the main design album:</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="287" />
      <location filename="../fontgallery/services/html_generation.py" line="232" />
      <location filename="../fontgallery/services/html_generation.py" line="176" />
      <source>Wrote HTML index for {label}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="182" />
      <source>Generated main HTML album: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="235" />
      <location filename="../fontgallery/services/html_generation.py" line="213" />
      <source>Spanish album</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="215" />
      <source>Album of fonts with Spanish support</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="216" />
      <source>Generated from the derived Spanish-support subset. These fonts are intended to cover accented Spanish characters and related glyphs.</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="238" />
      <source>Generated Spanish HTML album: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="290" />
      <location filename="../fontgallery/services/html_generation.py" line="268" />
      <source>Technical album</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="270" />
      <source>Album of technical and mathematical fonts</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="271" />
      <source>Generated for technical, mathematical, symbolic, or TeX-oriented fonts separated from the main design-focused album.</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="293" />
      <source>Generated technical HTML album: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="308" />
      <source>Missing extracted-font directory: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="320" />
      <source>No extracted fonts were found in: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="359" />
      <source>Classified as technical or mathematical</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="381" />
      <source>Indexed font {current}/{total_fonts} for {label}</source>
      <translation type="unfinished" />
    </message>
  </context>
  <context>
    <name>MainWindow</name>
    <message>
      <location filename="../fontgallery/main_window.py" line="83" />
      <source>FontGallery</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="84" />
      <source>Tool for preparing a workspace and automating visual font albums from .deb packages.</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="87" />
      <source>Workspace Status</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="88" />
      <source>Primary Actions</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="89" />
      <source>Optional Flat Card Folders</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="92" />
      <location filename="../fontgallery/main_window.py" line="90" />
      <source>Log</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="91" />
      <source>Workspace</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="93" />
      <source>Base folder</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="94" />
      <source>Item</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="95" />
      <source>Path</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="96" />
      <source>Status</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="97" />
      <source>Write access</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="99" />
      <source>Packages</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="108" />
      <location filename="../fontgallery/main_window.py" line="100" />
      <source>Main album</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="109" />
      <location filename="../fontgallery/main_window.py" line="101" />
      <source>Spanish album</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="110" />
      <location filename="../fontgallery/main_window.py" line="102" />
      <source>Technical album</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="103" />
      <source>Main cards</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="104" />
      <source>Spanish cards</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="105" />
      <source>Technical cards</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="112" />
      <source>1. Prepare workspace</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="113" />
      <source>2. Extract all fonts to the main album</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="114" />
      <source>3. Analyze and classify the master collection</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="115" />
      <source>4. Generate HTML indexes</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="116" />
      <source>5. Generate PNG cards</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="117" />
      <source>Refresh status</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="118" />
      <source>Copy main PNG cards to one root folder</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="119" />
      <source>Copy Spanish PNG cards to one root folder</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="120" />
      <source>Copy technical PNG cards to one root folder</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="121" />
      <source>These optional actions copy the generated PNG cards into a single root folder so you can browse them sequentially in an image viewer.</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="124" />
      <source>Flat folder</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="125" />
      <source>Ready.</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="126" />
      <source>Preparing workspace...</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="127" />
      <source>Extracting fonts...</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="128" />
      <source>Analyzing master collection...</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="129" />
      <source>Generating HTML indexes...</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="130" />
      <source>Generating PNG cards...</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="131" />
      <source>Completed.</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="132" />
      <source>Pending step</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="133" />
      <source>Step in progress</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="134" />
      <source>Completed and current step</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="135" />
      <source>Exists</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="136" />
      <source>Missing</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="137" />
      <source>Writable</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="138" />
      <source>Not writable</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="139" />
      <source>Detected .deb packages in '{folder}': {count}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="140" />
      <source>Error</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="141" />
      <source>Warning</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="142" />
      <source>File</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="143" />
      <source>Help</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="144" />
      <source>Exit</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="145" />
      <source>About...</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="146" />
      <source>About FontGallery</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="147" />
      <source>Desktop application for GNU/Linux that extracts fonts from .deb packages and builds visual HTML and PNG font albums.</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="150" />
      <source>Email</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="151" />
      <source>License</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="152" />
      <source>Website</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="153" />
      <source>Technologies used</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="154" />
      <source>Python 3, PyQt6, Pillow, Fontconfig, dpkg</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="155" />
      <source>Workspace ready</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="156" />
      <source>The base workspace structure was verified successfully.</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="157" />
      <source>Created folder: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="158" />
      <source>No folders needed to be created. The workspace already existed.</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="159" />
      <source>No packages</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="160" />
      <source>Extraction completed</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="161" />
      <source>Extraction into the main album finished.

Unique fonts: {unique}
Skipped duplicates: {duplicates}
Skipped broken fonts: {broken}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="167" />
      <source>Extraction summary: packages seen={seen}, font packages={font_packages}, unique fonts={unique}, skipped duplicates={duplicates}, skipped broken={broken}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="171" />
      <source>Extraction directory: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="172" />
      <source>Missing master collection</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="173" />
      <source>Analysis completed</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="174" />
      <source>The master collection was analyzed and classified.

Total fonts: {total}
Fonts with Spanish support: {spanish}
Technical fonts: {technical}
Copied to the Spanish album: {copied_spanish}
Copied to the technical album: {copied_technical}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="182" />
      <source>Analysis summary: total={total}, with Spanish support={spanish}, technical={technical}, copied to Spanish={copied_spanish}, copied to technical={copied_technical}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="186" />
      <source>Missing extracted fonts</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="187" />
      <source>HTML generation completed</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="188" />
      <source>The HTML font albums were generated successfully.

{details}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="191" />
      <source>PNG card generation completed</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="192" />
      <source>The PNG font cards were generated successfully.

{details}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="195" />
      <source>Flat PNG card folder created</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="196" />
      <source>Copied {count} PNG cards into:
{path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="199" />
      <source>HTML album '{label}': included={included}, excluded={excluded}, path={path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="202" />
      <source>PNG cards '{label}': generated={generated}, excluded={excluded}, render errors={errors}, path={path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="205" />
      <source>Exclusion report: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="206" />
      <source>An external tool failed:
{error}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="207" />
      <source>Could not prepare the workspace:
{error}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="208" />
      <source>Could not extract the fonts:
{error}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="209" />
      <source>Could not analyze the collection:
{error}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="210" />
      <source>Could not generate HTML indexes:
{error}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="211" />
      <source>Could not generate PNG cards:
{error}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="212" />
      <source>Could not create the flat PNG card folder:
{error}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="213" />
      <source>ERROR: {error}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="214" />
      <source>WARNING: {error}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="697" />
      <source>Copying {label} PNG cards into one root folder...</source>
      <translation type="unfinished" />
    </message>
  </context>
  <context>
    <name>WorkspaceService</name>
    <message>
      <location filename="../fontgallery/services/workspace.py" line="284" />
      <source>Verified workspace path: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/workspace.py" line="379" />
      <source>Expected a directory but found a file: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/workspace.py" line="386" />
      <source>Directory is not writable: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/workspace.py" line="396" />
      <source>Cannot create directory '{path}' because its parent is not writable: {parent}</source>
      <translation type="unfinished" />
    </message>
  </context>
</TS>
