<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1">
  <context>
    <name>AnalysisService</name>
    <message>
      <location filename="../fontgallery/services/analysis.py" line="137" />
      <source>The extracted master collection does not exist: {path}</source>
      <translation>No existe la colección maestra extraída: {path}</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/analysis.py" line="146" />
      <source>No extracted fonts were found in: {path}</source>
      <translation>No se encontraron fuentes extraídas en: {path}</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/analysis.py" line="162" />
      <source>Starting analysis of {count} extracted fonts</source>
      <translation>Iniciando análisis de {count} fuentes extraídas</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/analysis.py" line="192" />
      <source>Analyzed font {current}/{total_fonts}: {font}</source>
      <translation>Fuente analizada {current}/{total_fonts}: {font}</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/analysis.py" line="218" />
      <source>Copied Spanish subset: {count} fonts</source>
      <translation>Subconjunto en español copiado: {count} fuentes</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/analysis.py" line="234" />
      <source>Copied technical subset: {count} fonts</source>
      <translation>Subconjunto técnico copiado: {count} fuentes</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/analysis.py" line="268" />
      <source>Copied {count} fonts to {label}</source>
      <translation>Copiadas {count} fuentes a {label}</translation>
    </message>
  </context>
  <context>
    <name>CardGenerationService</name>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="80" />
      <source>Main album</source>
      <translation>Álbum principal</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="88" />
      <source>Spanish album</source>
      <translation>Álbum en español</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="96" />
      <source>Technical album</source>
      <translation>Álbum técnico</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="116" />
      <source>Starting PNG card generation</source>
      <translation>Iniciando generación de tarjetas PNG</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="169" />
      <source>Skipped card for {font} due to rendering error: {error}</source>
      <translation>Se omitió la tarjeta de {font} por un error de renderizado: {error}</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="180" />
      <source>Rendered card {current}/{total_cards} for {label}</source>
      <translation>Tarjeta renderizada {current}/{total_cards} para {label}</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="187" />
      <source>Generated {count} PNG cards for the {label} album in {path}</source>
      <translation>Generadas {count} tarjetas PNG para el álbum {label} en {path}</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="207" />
      <source>Missing extracted-font directory: {path}</source>
      <translation>Falta el directorio de fuentes extraídas: {path}</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="219" />
      <source>No extracted fonts were found in: {path}</source>
      <translation>No se encontraron fuentes extraídas en: {path}</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="304" />
      <source>Generated by FontGallery from locally extracted fonts.</source>
      <translation>Generado por FontGallery a partir de fuentes extraídas localmente.</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="318" />
      <source>Pillow is required for PNG card generation. Install the Python package 'Pillow' or the Debian package 'python3-pil'.</source>
      <translation>Pillow es obligatorio para generar tarjetas PNG. Instale el paquete de Python 'Pillow' o el paquete Debian 'python3-pil'.</translation>
    </message>
  </context>
  <context>
    <name>ExtractionService</name>
    <message>
      <location filename="../fontgallery/services/extraction.py" line="98" />
      <source>No font .deb packages were found in: {path}</source>
      <translation>No se encontraron paquetes .deb de fuentes en: {path}</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/extraction.py" line="114" />
      <source>Starting font extraction from {count} packages</source>
      <translation>Iniciando extracción de fuentes desde {count} paquetes</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/extraction.py" line="125" />
      <source>Processing package: {package}</source>
      <translation>Procesando paquete: {package}</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/extraction.py" line="164" />
      <source>  Accumulated fonts: {count}</source>
      <translation>  Fuentes acumuladas: {count}</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/extraction.py" line="173" />
      <source>Processed package {current}/{total}: {package}</source>
      <translation>Paquete procesado {current}/{total}: {package}</translation>
    </message>
  </context>
  <context>
    <name>FlatCardExportService</name>
    <message>
      <location filename="../fontgallery/services/flat_card_export.py" line="43" />
      <source>No PNG cards were found in: {path}</source>
      <translation>No se encontraron tarjetas PNG en: {path}</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/flat_card_export.py" line="58" />
      <source>Starting flat PNG export for the {label} album</source>
      <translation>Iniciando exportación plana de PNG para el álbum {label}</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/flat_card_export.py" line="70" />
      <source>Copied flat card {current}/{total}: {file}</source>
      <translation>Tarjeta plana copiada {current}/{total}: {file}</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/flat_card_export.py" line="78" />
      <source>Copied {count} PNG cards into the flat folder: {path}</source>
      <translation>Copiadas {count} tarjetas PNG en la carpeta plana: {path}</translation>
    </message>
  </context>
  <context>
    <name>HtmlGenerationService</name>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="119" />
      <source>Starting HTML generation for 3 albums</source>
      <translation>Iniciando generación HTML para 3 álbumes</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="189" />
      <location filename="../fontgallery/services/html_generation.py" line="157" />
      <source>Main album</source>
      <translation>Álbum principal</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="159" />
      <source>Album of extracted fonts from .deb packages</source>
      <translation>Álbum de fuentes extraídas desde paquetes .deb</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="160" />
      <source>Generated from locally extracted font packages and intended for general graphic design browsing. Technical and math-oriented fonts are excluded from this main album.</source>
      <translation>Generado a partir de paquetes de fuentes extraídos localmente y orientado a la exploración general para diseño gráfico. Las fuentes técnicas y matemáticas se excluyen de este álbum principal.</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="174" />
      <source>Technical fonts excluded from the main design album:</source>
      <translation>Fuentes técnicas excluidas del álbum principal de diseño:</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="297" />
      <location filename="../fontgallery/services/html_generation.py" line="242" />
      <location filename="../fontgallery/services/html_generation.py" line="186" />
      <source>Wrote HTML index for {label}</source>
      <translation>Índice HTML escrito para {label}</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="192" />
      <source>Generated main HTML album: {path}</source>
      <translation>Álbum HTML principal generado: {path}</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="245" />
      <location filename="../fontgallery/services/html_generation.py" line="223" />
      <source>Spanish album</source>
      <translation>Álbum en español</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="225" />
      <source>Album of fonts with Spanish support</source>
      <translation>Álbum de fuentes con soporte para español</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="226" />
      <source>Generated from the derived Spanish-support subset. These fonts are intended to cover accented Spanish characters and related glyphs.</source>
      <translation>Generado a partir del subconjunto derivado con soporte para español. Estas fuentes están pensadas para cubrir caracteres acentuados del español y glifos relacionados.</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="248" />
      <source>Generated Spanish HTML album: {path}</source>
      <translation>Álbum HTML en español generado: {path}</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="300" />
      <location filename="../fontgallery/services/html_generation.py" line="278" />
      <source>Technical album</source>
      <translation>Álbum técnico</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="280" />
      <source>Album of technical and mathematical fonts</source>
      <translation>Álbum de fuentes técnicas y matemáticas</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="281" />
      <source>Generated for technical, mathematical, symbolic, or TeX-oriented fonts separated from the main design-focused album.</source>
      <translation>Generado para fuentes técnicas, matemáticas, simbólicas o orientadas a TeX, separadas del álbum principal enfocado en diseño.</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="303" />
      <source>Generated technical HTML album: {path}</source>
      <translation>Álbum HTML técnico generado: {path}</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="318" />
      <source>Missing extracted-font directory: {path}</source>
      <translation>Falta el directorio de fuentes extraídas: {path}</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="330" />
      <source>No extracted fonts were found in: {path}</source>
      <translation>No se encontraron fuentes extraídas en: {path}</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="369" />
      <source>Classified as technical or mathematical</source>
      <translation>Clasificada como técnica o matemática</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="391" />
      <source>Indexed font {current}/{total_fonts} for {label}</source>
      <translation>Fuente indexada {current}/{total_fonts} para {label}</translation>
    </message>
  </context>
  <context>
    <name>MainWindow</name>
    <message>
      <location filename="../fontgallery/main_window.py" line="90" />
      <source>FontGallery</source>
      <translation>FontGallery</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="91" />
      <source>Tool for preparing a workspace and automating visual font albums from .deb packages.</source>
      <translation>Herramienta para preparar un espacio de trabajo y automatizar álbumes visuales de fuentes desde paquetes .deb.</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="94" />
      <source>Workspace Status</source>
      <translation>Estado del espacio de trabajo</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="95" />
      <source>Primary Actions</source>
      <translation>Acciones principales</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="96" />
      <source>Optional Flat Card Folders</source>
      <translation>Carpetas opcionales de tarjetas planas</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="99" />
      <location filename="../fontgallery/main_window.py" line="97" />
      <source>Log</source>
      <translation>Registro</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="98" />
      <source>Workspace</source>
      <translation>Espacio de trabajo</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="100" />
      <source>Card Text</source>
      <translation>Texto de tarjeta</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="101" />
      <source>Base folder</source>
      <translation>Carpeta base</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="102" />
      <source>Item</source>
      <translation>Elemento</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="103" />
      <source>Path</source>
      <translation>Ruta</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="104" />
      <source>Status</source>
      <translation>Estado</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="105" />
      <source>Write access</source>
      <translation>Acceso de escritura</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="107" />
      <source>Packages</source>
      <translation>Paquetes</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="116" />
      <location filename="../fontgallery/main_window.py" line="108" />
      <source>Main album</source>
      <translation>Álbum principal</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="117" />
      <location filename="../fontgallery/main_window.py" line="109" />
      <source>Spanish album</source>
      <translation>Álbum en español</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="118" />
      <location filename="../fontgallery/main_window.py" line="110" />
      <source>Technical album</source>
      <translation>Álbum técnico</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="111" />
      <source>Main cards</source>
      <translation>Tarjetas principales</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="112" />
      <source>Spanish cards</source>
      <translation>Tarjetas en español</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="113" />
      <source>Technical cards</source>
      <translation>Tarjetas técnicas</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="120" />
      <source>1. Prepare workspace</source>
      <translation>1. Preparar espacio de trabajo</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="121" />
      <source>2. Extract all fonts to the main album</source>
      <translation>2. Extraer todas las fuentes al álbum principal</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="122" />
      <source>3. Analyze and classify the master collection</source>
      <translation>3. Analizar y clasificar la colección maestra</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="123" />
      <source>4. Generate HTML indexes</source>
      <translation>4. Generar índices HTML</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="124" />
      <source>5. Generate PNG cards</source>
      <translation>5. Generar tarjetas PNG</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="125" />
      <source>Refresh status</source>
      <translation>Actualizar estado</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="126" />
      <source>Copy main PNG cards to one root folder</source>
      <translation>Copiar las tarjetas PNG principales a una carpeta raíz</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="127" />
      <source>Copy Spanish PNG cards to one root folder</source>
      <translation>Copiar las tarjetas PNG en español a una carpeta raíz</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="128" />
      <source>Copy technical PNG cards to one root folder</source>
      <translation>Copiar las tarjetas PNG técnicas a una carpeta raíz</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="129" />
      <source>These optional actions copy the generated PNG cards into a single root folder so you can browse them sequentially in an image viewer.</source>
      <translation>Estas acciones opcionales copian las tarjetas PNG generadas a una sola carpeta raíz para que puedas verlas de forma secuencial en un visor de imágenes.</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="132" />
      <source>Flat folder</source>
      <translation>Carpeta plana</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="133" />
      <source>Long text used in PNG cards</source>
      <translation>Texto largo usado en las tarjetas PNG</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="134" />
      <source>Edit the long text shown in the main and Spanish PNG cards. The alphabet and symbol sample stays unchanged.</source>
      <translation>Edita el texto largo que se muestra en las tarjetas PNG principales y en español. La muestra de alfabeto y símbolos no cambia.</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="137" />
      <source>Restore default text</source>
      <translation>Restaurar texto predeterminado</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="138" />
      <source>Words: {words}/{max_words} | Characters: {chars}/{max_chars}</source>
      <translation>Palabras: {words}/{max_words} | Caracteres: {chars}/{max_chars}</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="139" />
      <source>The card text is too long for reliable PNG rendering.</source>
      <translation>El texto de la tarjeta es demasiado largo para un renderizado PNG confiable.</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="140" />
      <source>Ready.</source>
      <translation>Listo.</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="141" />
      <source>Preparing workspace...</source>
      <translation>Preparando espacio de trabajo...</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="142" />
      <source>Extracting fonts...</source>
      <translation>Extrayendo fuentes...</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="143" />
      <source>Analyzing master collection...</source>
      <translation>Analizando colección maestra...</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="144" />
      <source>Generating HTML indexes...</source>
      <translation>Generando índices HTML...</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="145" />
      <source>Generating PNG cards...</source>
      <translation>Generando tarjetas PNG...</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="146" />
      <source>Completed.</source>
      <translation>Completado.</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="147" />
      <source>Pending step</source>
      <translation>Paso pendiente</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="148" />
      <source>Step in progress</source>
      <translation>Paso en ejecución</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="149" />
      <source>Completed and current step</source>
      <translation>Paso completado y vigente</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="150" />
      <source>Exists</source>
      <translation>Existe</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="151" />
      <source>Missing</source>
      <translation>No existe</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="152" />
      <source>Writable</source>
      <translation>Con escritura</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="153" />
      <source>Not writable</source>
      <translation>Sin escritura</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="154" />
      <source>Detected .deb packages in '{folder}': {count}</source>
      <translation>Paquetes .deb detectados en '{folder}': {count}</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="155" />
      <source>Error</source>
      <translation>Error</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="156" />
      <source>Warning</source>
      <translation>Aviso</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="157" />
      <source>File</source>
      <translation>Archivo</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="158" />
      <source>Help</source>
      <translation>Ayuda</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="159" />
      <source>Exit</source>
      <translation>Salir</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="160" />
      <source>About...</source>
      <translation>Acerca de...</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="161" />
      <source>About FontGallery</source>
      <translation>Acerca de FontGallery</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="162" />
      <source>Desktop application for GNU/Linux that extracts fonts from .deb packages and builds visual HTML and PNG font albums.</source>
      <translation>Aplicación de escritorio para GNU/Linux que extrae fuentes desde paquetes .deb y construye álbumes visuales de fuentes en HTML y PNG.</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="165" />
      <source>Email</source>
      <translation>Correo</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="166" />
      <source>License</source>
      <translation>Licencia</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="167" />
      <source>Website</source>
      <translation>Página web</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="168" />
      <source>Technologies used</source>
      <translation>Tecnologías usadas</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="169" />
      <source>Python 3, PyQt6, Pillow, Fontconfig, dpkg</source>
      <translation>Python 3, PyQt6, Pillow, Fontconfig, dpkg</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="170" />
      <source>Workspace ready</source>
      <translation>Espacio de trabajo listo</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="171" />
      <source>The base workspace structure was verified successfully.</source>
      <translation>La estructura base del espacio de trabajo fue verificada correctamente.</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="172" />
      <source>Created folder: {path}</source>
      <translation>Carpeta creada: {path}</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="173" />
      <source>No folders needed to be created. The workspace already existed.</source>
      <translation>No fue necesario crear carpetas. El espacio de trabajo ya existía.</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="174" />
      <source>No packages</source>
      <translation>Sin paquetes</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="175" />
      <source>Extraction completed</source>
      <translation>Extracción completada</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="176" />
      <source>Extraction into the main album finished.

Unique fonts: {unique}
Skipped duplicates: {duplicates}
Skipped broken fonts: {broken}</source>
      <translation>La extracción al álbum principal terminó.

Fuentes únicas: {unique}
Duplicadas omitidas: {duplicates}
Fuentes dañadas omitidas: {broken}</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="182" />
      <source>Extraction summary: packages seen={seen}, font packages={font_packages}, unique fonts={unique}, skipped duplicates={duplicates}, skipped broken={broken}</source>
      <translation>Resumen de extracción: paquetes vistos={seen}, paquetes de fuentes={font_packages}, fuentes únicas={unique}, duplicadas omitidas={duplicates}, dañadas omitidas={broken}</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="186" />
      <source>Extraction directory: {path}</source>
      <translation>Directorio de extracción: {path}</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="187" />
      <source>Missing master collection</source>
      <translation>Falta la colección maestra</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="188" />
      <source>Analysis completed</source>
      <translation>Análisis completado</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="189" />
      <source>The master collection was analyzed and classified.

Total fonts: {total}
Fonts with Spanish support: {spanish}
Technical fonts: {technical}
Copied to the Spanish album: {copied_spanish}
Copied to the technical album: {copied_technical}</source>
      <translation>La colección maestra fue analizada y clasificada.

Fuentes totales: {total}
Fuentes con soporte para español: {spanish}
Fuentes técnicas: {technical}
Copiadas al álbum en español: {copied_spanish}
Copiadas al álbum técnico: {copied_technical}</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="197" />
      <source>Analysis summary: total={total}, with Spanish support={spanish}, technical={technical}, copied to Spanish={copied_spanish}, copied to technical={copied_technical}</source>
      <translation>Resumen de análisis: total={total}, con soporte para español={spanish}, técnicas={technical}, copiadas a español={copied_spanish}, copiadas a técnico={copied_technical}</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="201" />
      <source>Missing extracted fonts</source>
      <translation>Faltan fuentes extraídas</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="202" />
      <source>HTML generation completed</source>
      <translation>Generación HTML completada</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="203" />
      <source>The HTML font albums were generated successfully.

{details}</source>
      <translation>Los álbumes HTML de fuentes se generaron correctamente.

{details}</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="206" />
      <source>PNG card generation completed</source>
      <translation>Generación de tarjetas PNG completada</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="207" />
      <source>The PNG font cards were generated successfully.

{details}</source>
      <translation>Las tarjetas PNG de fuentes se generaron correctamente.

{details}</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="210" />
      <source>Flat PNG card folder created</source>
      <translation>Carpeta plana de tarjetas PNG creada</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="211" />
      <source>Copied {count} PNG cards into:
{path}</source>
      <translation>Copiadas {count} tarjetas PNG en:
{path}</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="214" />
      <source>HTML album '{label}': included={included}, excluded={excluded}, path={path}</source>
      <translation>Álbum HTML '{label}': incluidas={included}, excluidas={excluded}, ruta={path}</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="217" />
      <source>PNG cards '{label}': generated={generated}, excluded={excluded}, render errors={errors}, path={path}</source>
      <translation>Tarjetas PNG '{label}': generadas={generated}, excluidas={excluded}, errores de renderizado={errors}, ruta={path}</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="220" />
      <source>Exclusion report: {path}</source>
      <translation>Reporte de exclusión: {path}</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="221" />
      <source>An external tool failed:
{error}</source>
      <translation>Falló una herramienta externa:
{error}</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="222" />
      <source>Could not prepare the workspace:
{error}</source>
      <translation>No se pudo preparar el espacio de trabajo:
{error}</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="223" />
      <source>Could not extract the fonts:
{error}</source>
      <translation>No se pudieron extraer las fuentes:
{error}</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="224" />
      <source>Could not analyze the collection:
{error}</source>
      <translation>No se pudo analizar la colección:
{error}</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="225" />
      <source>Could not generate HTML indexes:
{error}</source>
      <translation>No se pudieron generar los índices HTML:
{error}</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="226" />
      <source>Could not generate PNG cards:
{error}</source>
      <translation>No se pudieron generar las tarjetas PNG:
{error}</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="227" />
      <source>Card text too long</source>
      <translation>Texto de tarjeta demasiado largo</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="228" />
      <source>Could not create the flat PNG card folder:
{error}</source>
      <translation>No se pudo crear la carpeta plana de tarjetas PNG:
{error}</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="229" />
      <source>ERROR: {error}</source>
      <translation>ERROR: {error}</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="230" />
      <source>WARNING: {error}</source>
      <translation>AVISO: {error}</translation>
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="752" />
      <source>Copying {label} PNG cards into one root folder...</source>
      <translation>Copiando las tarjetas PNG de {label} a una sola carpeta raíz...</translation>
    </message>
    <message>
      <source>Optional: copy main PNG cards into one root folder</source>
      <translation type="vanished">Opcional: copiar las tarjetas PNG principales a una sola carpeta raíz</translation>
    </message>
    <message>
      <source>Optional: copy Spanish PNG cards into one root folder</source>
      <translation type="vanished">Opcional: copiar las tarjetas PNG en español a una sola carpeta raíz</translation>
    </message>
    <message>
      <source>Optional: copy technical PNG cards into one root folder</source>
      <translation type="vanished">Opcional: copiar las tarjetas PNG técnicas a una sola carpeta raíz</translation>
    </message>
    <message>
      <source>Prepare workspace</source>
      <translation type="vanished">Preparar espacio de trabajo</translation>
    </message>
    <message>
      <source>Extract all fonts to the main album</source>
      <translation type="vanished">Extraer todas las fuentes al álbum principal</translation>
    </message>
    <message>
      <source>Analyze and classify the master collection</source>
      <translation type="vanished">Analizar y clasificar la colección maestra</translation>
    </message>
    <message>
      <source>Generate HTML indexes</source>
      <translation type="vanished">Generar índices HTML</translation>
    </message>
    <message>
      <source>Generate PNG cards</source>
      <translation type="vanished">Generar tarjetas PNG</translation>
    </message>
  </context>
  <context>
    <name>WorkspaceService</name>
    <message>
      <location filename="../fontgallery/services/workspace.py" line="284" />
      <source>Verified workspace path: {path}</source>
      <translation>Ruta del espacio de trabajo verificada: {path}</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/workspace.py" line="379" />
      <source>Expected a directory but found a file: {path}</source>
      <translation>Se esperaba un directorio pero se encontró un archivo: {path}</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/workspace.py" line="386" />
      <source>Directory is not writable: {path}</source>
      <translation>El directorio no tiene permiso de escritura: {path}</translation>
    </message>
    <message>
      <location filename="../fontgallery/services/workspace.py" line="396" />
      <source>Cannot create directory '{path}' because its parent is not writable: {parent}</source>
      <translation>No se puede crear el directorio '{path}' porque su carpeta padre no tiene permiso de escritura: {parent}</translation>
    </message>
  </context>
</TS>
