<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1">
  <context>
    <name>AnalysisService</name>
    <message>
      <location filename="../fontgallery/services/analysis.py" line="136" />
      <source>The extracted master collection does not exist: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/analysis.py" line="145" />
      <source>No extracted fonts were found in: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/analysis.py" line="225" />
      <source>Copied {count} fonts to {label}</source>
      <translation type="unfinished" />
    </message>
  </context>
  <context>
    <name>CardGenerationService</name>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="128" />
      <source>Skipped card for {font} due to rendering error: {error}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="137" />
      <source>Generated {count} PNG cards for the {label} album in {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="157" />
      <source>Missing extracted-font directory: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="169" />
      <source>No extracted fonts were found in: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="240" />
      <source>Generated by FontGallery from locally extracted fonts.</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/card_generation.py" line="254" />
      <source>Pillow is required for PNG card generation. Install the Python package 'Pillow' or the Debian package 'python3-pil'.</source>
      <translation type="unfinished" />
    </message>
  </context>
  <context>
    <name>ExtractionService</name>
    <message>
      <location filename="../fontgallery/services/extraction.py" line="97" />
      <source>No font .deb packages were found in: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/extraction.py" line="113" />
      <source>Processing package: {package}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/extraction.py" line="152" />
      <source>  Accumulated fonts: {count}</source>
      <translation type="unfinished" />
    </message>
  </context>
  <context>
    <name>HtmlGenerationService</name>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="111" />
      <source>Album of extracted fonts from .deb packages</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="112" />
      <source>Generated from locally extracted font packages and intended for general graphic design browsing. Technical and math-oriented fonts are excluded from this main album.</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="126" />
      <source>Technical fonts excluded from the main design album:</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="135" />
      <source>Generated main HTML album: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="158" />
      <source>Album of fonts with Spanish support</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="159" />
      <source>Generated from the derived Spanish-support subset. These fonts are intended to cover accented Spanish characters and related glyphs.</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="172" />
      <source>Generated Spanish HTML album: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="194" />
      <source>Album of technical and mathematical fonts</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="195" />
      <source>Generated for technical, mathematical, symbolic, or TeX-oriented fonts separated from the main design-focused album.</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="208" />
      <source>Generated technical HTML album: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="228" />
      <source>Missing extracted-font directory: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="240" />
      <source>No extracted fonts were found in: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/html_generation.py" line="267" />
      <source>Classified as technical or mathematical</source>
      <translation type="unfinished" />
    </message>
  </context>
  <context>
    <name>MainWindow</name>
    <message>
      <location filename="../fontgallery/main_window.py" line="48" />
      <location filename="../fontgallery/main_window.py" line="47" />
      <source>FontGallery</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="49" />
      <source>Tool for preparing a workspace and automating visual font albums from .deb packages.</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="52" />
      <source>Workspace Status</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="53" />
      <source>Primary Actions</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="54" />
      <source>Log</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="55" />
      <source>Base folder</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="56" />
      <source>Item</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="57" />
      <source>Path</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="58" />
      <source>Status</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="59" />
      <source>Write access</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="61" />
      <source>Packages</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="67" />
      <location filename="../fontgallery/main_window.py" line="62" />
      <source>Main album</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="68" />
      <location filename="../fontgallery/main_window.py" line="63" />
      <source>Spanish album</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="69" />
      <location filename="../fontgallery/main_window.py" line="64" />
      <source>Technical album</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="71" />
      <source>Prepare workspace</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="72" />
      <source>Extract all fonts to the main album</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="73" />
      <source>Analyze and classify the master collection</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="74" />
      <source>Generate HTML indexes</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="75" />
      <source>Generate PNG cards</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="76" />
      <source>Refresh status</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="77" />
      <source>Exists</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="78" />
      <source>Missing</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="79" />
      <source>Writable</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="80" />
      <source>Not writable</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="81" />
      <source>Detected .deb packages in '{folder}': {count}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="82" />
      <source>Error</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="83" />
      <source>Warning</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="84" />
      <source>Workspace ready</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="85" />
      <source>The base workspace structure was verified successfully.</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="86" />
      <source>Created folder: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="87" />
      <source>No folders needed to be created. The workspace already existed.</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="88" />
      <source>No packages</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="89" />
      <source>Extraction completed</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="90" />
      <source>Extraction into the main album finished.

Unique fonts: {unique}
Skipped duplicates: {duplicates}
Skipped broken fonts: {broken}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="96" />
      <source>Extraction summary: packages seen={seen}, font packages={font_packages}, unique fonts={unique}, skipped duplicates={duplicates}, skipped broken={broken}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="100" />
      <source>Extraction directory: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="101" />
      <source>Missing master collection</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="102" />
      <source>Analysis completed</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="103" />
      <source>The master collection was analyzed and classified.

Total fonts: {total}
Fonts with Spanish support: {spanish}
Technical fonts: {technical}
Copied to the Spanish album: {copied_spanish}
Copied to the technical album: {copied_technical}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="111" />
      <source>Analysis summary: total={total}, with Spanish support={spanish}, technical={technical}, copied to Spanish={copied_spanish}, copied to technical={copied_technical}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="115" />
      <source>Missing extracted fonts</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="116" />
      <source>HTML generation completed</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="117" />
      <source>The HTML font albums were generated successfully.

{details}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="120" />
      <source>PNG card generation completed</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="121" />
      <source>The PNG font cards were generated successfully.

{details}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="124" />
      <source>HTML album '{label}': included={included}, excluded={excluded}, path={path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="127" />
      <source>PNG cards '{label}': generated={generated}, excluded={excluded}, render errors={errors}, path={path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="130" />
      <source>Exclusion report: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="131" />
      <source>An external tool failed:
{error}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="132" />
      <source>Could not prepare the workspace:
{error}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="133" />
      <source>Could not extract the fonts:
{error}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="134" />
      <source>Could not analyze the collection:
{error}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="135" />
      <source>Could not generate HTML indexes:
{error}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="136" />
      <source>Could not generate PNG cards:
{error}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="137" />
      <source>ERROR: {error}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/main_window.py" line="138" />
      <source>WARNING: {error}</source>
      <translation type="unfinished" />
    </message>
  </context>
  <context>
    <name>WorkspaceService</name>
    <message>
      <location filename="../fontgallery/services/workspace.py" line="320" />
      <source>Expected a directory but found a file: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/workspace.py" line="327" />
      <source>Directory is not writable: {path}</source>
      <translation type="unfinished" />
    </message>
    <message>
      <location filename="../fontgallery/services/workspace.py" line="337" />
      <source>Cannot create directory '{path}' because its parent is not writable: {parent}</source>
      <translation type="unfinished" />
    </message>
  </context>
</TS>
